SELECT
	t2.TABLE_NAME,
	--t2.COLUMN_NAME,
	t3.TABLE_NAME AS ChildrenTableName--,
	--t3.COLUMN_NAME AS ChildrenColumnId
FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS AS t1 
	INNER JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE AS t2 ON t1.UNIQUE_CONSTRAINT_NAME = t2.CONSTRAINT_NAME
	INNER JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE AS t3 ON t1.CONSTRAINT_NAME = t3.CONSTRAINT_NAME
--WHERE 
ORDER BY t2.TABLE_NAME;